// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: preset/preset.proto

package preset

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoParamEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoParamEntry) Reset() {
	*x = ProtoParamEntry{}
	mi := &file_preset_preset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoParamEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoParamEntry) ProtoMessage() {}

func (x *ProtoParamEntry) ProtoReflect() protoreflect.Message {
	mi := &file_preset_preset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoParamEntry.ProtoReflect.Descriptor instead.
func (*ProtoParamEntry) Descriptor() ([]byte, []int) {
	return file_preset_preset_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoParamEntry) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProtoParamEntry) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProtoPreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Params        []*ProtoParamEntry     `protobuf:"bytes,1,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoPreset) Reset() {
	*x = ProtoPreset{}
	mi := &file_preset_preset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoPreset) ProtoMessage() {}

func (x *ProtoPreset) ProtoReflect() protoreflect.Message {
	mi := &file_preset_preset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoPreset.ProtoReflect.Descriptor instead.
func (*ProtoPreset) Descriptor() ([]byte, []int) {
	return file_preset_preset_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoPreset) GetParams() []*ProtoParamEntry {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_preset_preset_proto protoreflect.FileDescriptor

const file_preset_preset_proto_rawDesc = "" +
	"\n" +
	"\x13preset/preset.proto\x12\x06preset\"7\n" +
	"\x0fProtoParamEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\">\n" +
	"\vProtoPreset\x12/\n" +
	"\x06params\x18\x01 \x03(\v2\x17.preset.ProtoParamEntryR\x06paramsB\tZ\a/presetb\x06proto3"

var (
	file_preset_preset_proto_rawDescOnce sync.Once
	file_preset_preset_proto_rawDescData []byte
)

func file_preset_preset_proto_rawDescGZIP() []byte {
	file_preset_preset_proto_rawDescOnce.Do(func() {
		file_preset_preset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_preset_preset_proto_rawDesc), len(file_preset_preset_proto_rawDesc)))
	})
	return file_preset_preset_proto_rawDescData
}

var file_preset_preset_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_preset_preset_proto_goTypes = []any{
	(*ProtoParamEntry)(nil), // 0: preset.ProtoParamEntry
	(*ProtoPreset)(nil),     // 1: preset.ProtoPreset
}
var file_preset_preset_proto_depIdxs = []int32{
	0, // 0: preset.ProtoPreset.params:type_name -> preset.ProtoParamEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_preset_preset_proto_init() }
func file_preset_preset_proto_init() {
	if File_preset_preset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_preset_preset_proto_rawDesc), len(file_preset_preset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_preset_preset_proto_goTypes,
		DependencyIndexes: file_preset_preset_proto_depIdxs,
		MessageInfos:      file_preset_preset_proto_msgTypes,
	}.Build()
	File_preset_preset_proto = out.File
	file_preset_preset_proto_goTypes = nil
	file_preset_preset_proto_depIdxs = nil
}
