// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: settings/settings.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtoSetting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSetting) Reset() {
	*x = ProtoSetting{}
	mi := &file_settings_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSetting) ProtoMessage() {}

func (x *ProtoSetting) ProtoReflect() protoreflect.Message {
	mi := &file_settings_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSetting.ProtoReflect.Descriptor instead.
func (*ProtoSetting) Descriptor() ([]byte, []int) {
	return file_settings_settings_proto_rawDescGZIP(), []int{0}
}

func (x *ProtoSetting) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProtoSetting) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ProtoSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*ProtoSetting        `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoSettings) Reset() {
	*x = ProtoSettings{}
	mi := &file_settings_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoSettings) ProtoMessage() {}

func (x *ProtoSettings) ProtoReflect() protoreflect.Message {
	mi := &file_settings_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoSettings.ProtoReflect.Descriptor instead.
func (*ProtoSettings) Descriptor() ([]byte, []int) {
	return file_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *ProtoSettings) GetSettings() []*ProtoSetting {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_settings_settings_proto protoreflect.FileDescriptor

const file_settings_settings_proto_rawDesc = "" +
	"\n" +
	"\x17settings/settings.proto\x12\bsettings\"4\n" +
	"\fProtoSetting\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"C\n" +
	"\rProtoSettings\x122\n" +
	"\bsettings\x18\x01 \x03(\v2\x16.settings.ProtoSettingR\bsettingsB\vZ\t/settingsb\x06proto3"

var (
	file_settings_settings_proto_rawDescOnce sync.Once
	file_settings_settings_proto_rawDescData []byte
)

func file_settings_settings_proto_rawDescGZIP() []byte {
	file_settings_settings_proto_rawDescOnce.Do(func() {
		file_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settings_settings_proto_rawDesc), len(file_settings_settings_proto_rawDesc)))
	})
	return file_settings_settings_proto_rawDescData
}

var file_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_settings_proto_goTypes = []any{
	(*ProtoSetting)(nil),  // 0: settings.ProtoSetting
	(*ProtoSettings)(nil), // 1: settings.ProtoSettings
}
var file_settings_settings_proto_depIdxs = []int32{
	0, // 0: settings.ProtoSettings.settings:type_name -> settings.ProtoSetting
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_settings_settings_proto_init() }
func file_settings_settings_proto_init() {
	if File_settings_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settings_settings_proto_rawDesc), len(file_settings_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_settings_settings_proto_goTypes,
		DependencyIndexes: file_settings_settings_proto_depIdxs,
		MessageInfos:      file_settings_settings_proto_msgTypes,
	}.Build()
	File_settings_settings_proto = out.File
	file_settings_settings_proto_goTypes = nil
	file_settings_settings_proto_depIdxs = nil
}
