package ui

import "synth/preset"

func NewTree() Node {
	return NewListNode("",
		NewListNode("Oscillators",
			NewListNode("Oscillator 1",
				NewListNode("Waveform"),
				NewListNode("Octave"),
				NewListNode("Semitone"),
				NewListNode("Detune"),
				NewListNode("Gain"),
			),
			NewListNode("Oscillator 2",
				NewListNode("Waveform"),
				NewListNode("Octave"),
				NewListNode("Semitone"),
				NewListNode("Detune"),
				NewListNode("Gain"),
			),
			NewListNode("Oscillator 3",
				NewListNode("Waveform"),
				NewListNode("Octave"),
				NewListNode("Semitone"),
				NewListNode("Detune"),
				NewListNode("Gain"),
			),
		),
		NewListNode("Modulation",
			NewListNode("Amplitude"),
			NewListNode("Cutoff"),
			NewListNode("Resonance"),
			NewListNode("Pitch"),
		),
		NewListNode("Effects",
			NewListNode("Feedback delay",
				NewSliderNode("Delay", "ms", preset.FBDelayParam, 0, 2000, 1),
			),
			NewListNode("Low pass filter"),
			NewListNode("Unison",
				NewListNode("Voices"),
				NewListNode("Pan spread"),
				NewListNode("Phase spread"),
			),
		),
		NewListNode("Visualizer",
			NewListNode("Spectrum"),
			NewListNode("Oscilloscope"),
		),
		NewListNode("Presets",
			NewListNode("Load preset"),
			NewListNode("Save preset"),
			// Todo ON/OFF, add toggle node
			NewListNode("Auto save"),
		),
		NewListNode("Settings",
			NewListNode("General"),
			NewListNode("Master gain"),
			NewListNode("MIDI controller"),
			NewListNode("Pitch bend"),
			NewListNode("About"),
		),
	)
}
