package tree

import (
	"synth/dsp"
	"synth/preset"
	"synth/settings"
)

func NewTree(presets []string) Node {
	return NewNode("",
		NewNode("Oscillators",
			NewOscillatorNode("Oscillator 1", preset.Osc0Shape, preset.Osc0Detune, preset.Osc0Gain, preset.Osc0Phase, preset.Osc0Pw),
			NewOscillatorNode("Oscillator 2", preset.Osc0Shape, preset.Osc0Detune, preset.Osc0Gain, preset.Osc0Phase, preset.Osc0Pw),
			NewOscillatorNode("Oscillator 3", preset.Osc0Shape, preset.Osc0Detune, preset.Osc0Gain, preset.Osc0Phase, preset.Osc0Pw),
		),
		NewNode("Modulation",
			NewAdsrNode("Amplitude", preset.AmpEnvAttack, preset.AmpEnvDecay, preset.AmpEnvSustain, preset.AmpEnvRelease),
			NewNode("Cutoff",
				NewNode("LFO",
					NewOnOffNode(preset.LpfLfoOnOff),
					NewSliderNode("Amount", preset.PresetUpdateKind, preset.LpfLfoAmount, 20, 20000, 1, formatHertz),
					NewWaveFormNode(preset.LpfLfoShape),
					NewSliderNode("Rate", preset.PresetUpdateKind, preset.LpfLfoFreq, 0.01, 20, .01, formatLowHertz),
					NewSliderNode("Phase", preset.PresetUpdateKind, preset.LpfLfoPhase, 0, 1, .01, formatCycle),
				),
				NewAdsrNodeWithToggle("ADSR", preset.LpfAdsrOnOff, preset.LpfAdsrAttack, preset.LpfAdsrDecay, preset.LpfAdsrSustain, preset.LpfAdsrRelease,
					NewSliderNode("Amount", preset.PresetUpdateKind, preset.LpfAdsrAmount, -20000, 20000, 1, formatHertz),
				),
			),
			NewNode("Pitch",
				NewNode("LFO",
					NewOnOffNode(preset.PitchLfoOnOff),
					NewSliderNode("Amount", preset.PresetUpdateKind, preset.PitchLfoAmount, -1000, 1000, .01, formatSemiTon),
					NewWaveFormNode(preset.PitchLfoShape),
					NewSliderNode("Rate", preset.PresetUpdateKind, preset.PitchLfoFreq, 0.01, 20, .01, formatLowHertz),
					NewSliderNode("Phase", preset.PresetUpdateKind, preset.PitchLfoPhase, 0, 1, .01, formatCycle),
				),
				NewAdsrNodeWithToggle("ADSR", preset.PitchAdsrOnOff, preset.PitchAdsrAttack, preset.PitchAdsrDecay, preset.PitchAdsrSustain, preset.PitchAdsrRelease,
					NewSliderNode("Amount", preset.PresetUpdateKind, preset.PitchAdsrAmount, -1000, 1000, .01, formatSemiTon),
				),
			),
		),
		NewNode("Effects",
			NewNode("Feedback delay",
				NewOnOffNode(preset.FBOnOff),
				NewSliderNode("Delay", preset.PresetUpdateKind, preset.FBDelayParam, 0, 2, .001, formatMillisecond),
				NewSliderNode("Feedback", preset.PresetUpdateKind, preset.FBFeedBack, 0, 0.95, .01, nil),
				NewSliderNode("Mix", preset.PresetUpdateKind, preset.FBMix, 0, 1, .01, nil),
				NewSliderNode("Tone", preset.PresetUpdateKind, preset.FBTone, 200, 8000, 1, formatHertz),
			),
			NewNode("Low pass filter",
				NewOnOffNode(preset.LPFOnOff),
				NewSliderNode("Cutoff", preset.PresetUpdateKind, preset.LPFCutoff, 20, 20000, 1, formatHertz),
				NewSliderNode("Resonance", preset.PresetUpdateKind, preset.LPFResonance, 0.01, 10, .01, nil),
			),
			NewNode("Unison",
				NewOnOffNode(preset.UnisonOnOff),
				NewSliderNode("Voices", preset.PresetUpdateKind, preset.UnisonVoices, 1, 16, 1, formatVoice),
				NewSliderNode("Pan spread", preset.PresetUpdateKind, preset.UnisonPanSpread, 0, 1, .01, nil),
				NewSliderNode("Phase spread", preset.PresetUpdateKind, preset.UnisonPhaseSpread, 0, 1, .01, formatCycle),
				NewSliderNode("Detune spread", preset.PresetUpdateKind, preset.UnisonDetuneSpread, 0, 100, .1, formatCent),
				NewSliderNode("Curve gamma", preset.PresetUpdateKind, preset.UnisonCurveGamma, 0.1, 4, .1, nil),
			),
		),
		NewNode("Voices",
			NewSelectorNode("Steal mode", preset.PresetUpdateKind, preset.VoicesStealMode,
				NewSelectorOption("Oldest", "", dsp.PolyStealOldest),
				NewSelectorOption("Lowest pitch", "", dsp.PolyStealLowest),
				NewSelectorOption("Highest pitch", "", dsp.PolyStealHighest),
			),
			NewSliderNode("Active voices", preset.PresetUpdateKind, preset.VoicesActive, 1, 16, 1, formatVoice),
			NewSliderNode("Pitch glide", preset.PresetUpdateKind, preset.VoicesPitchGlide, 0, 1, .001, formatMillisecond),
		),
		NewNode("Visualizer",
			NewFeatureNode("Spectrum", 0), // todo implement spectrum analyzer
			NewFeatureNode("Oscilloscope", FeatureOscilloscope),
		),
		NewNode("Presets",
			NewPresetsNodes(presets)...,
		),
		NewNode("Settings",
			NewSliderNode("Master gain", settings.SettingUpdateKind, settings.MasterGain, 0, 3, .01, nil),
			NewSliderNode("Pitch bend range", settings.SettingUpdateKind, settings.PitchBendRange, 1, 24, 1, formatSemiTon),
		),
	)
}
