package tree

import (
	"fmt"
	"synth/preset"

	"github.com/rs/zerolog"
)

func buildTree(logger zerolog.Logger) Node {
	return NewNode("",
		NewNode("Oscillators",
			NewNode("Oscillator 1",
				waveFormNode(preset.Osc0Shape),
				NewSliderNode("Detune", preset.Osc0Detune, -100, 100, .01, formatSemiTon),
				NewSliderNode("Gain", preset.Osc0Gain, 0, 1, .01, nil),
				NewSliderNode("Phase", preset.Osc0Phase, 0, 1, .01, formatCycle),
				NewSliderNode("Pulse width", preset.Osc0Pw, 0.01, 0.5, .01, nil),
			),
			NewNode("Oscillator 2",
				waveFormNode(preset.Osc1Shape),
				NewSliderNode("Detune", preset.Osc1Detune, -100, 100, .01, formatSemiTon),
				NewSliderNode("Gain", preset.Osc1Gain, 0, 1, .01, nil),
				NewSliderNode("Phase", preset.Osc1Phase, 0, 1, .01, formatCycle),
				NewSliderNode("Pulse width", preset.Osc1Pw, 0.01, 0.5, .01, nil),
			),
			NewNode("Oscillator 3",
				waveFormNode(preset.Osc2Shape),
				NewSliderNode("Detune", preset.Osc2Detune, -100, 100, .01, formatSemiTon),
				NewSliderNode("Gain", preset.Osc2Gain, 0, 1, .01, nil),
				NewSliderNode("Phase", preset.Osc2Phase, 0, 1, .01, formatCycle),
				NewSliderNode("Pulse width", preset.Osc2Pw, 0.01, 0.5, .01, nil),
			),
		),
		NewNode("Modulation",
			adsrNode("Amplitude", preset.AmpEnvAttack, preset.AmpEnvDecay, preset.AmpEnvSustain, preset.AmpEnvRelease),
			NewNode("Cutoff",
				NewNode("LFO",
					onOffNode(preset.LpfLfoOnOff),
					NewSliderNode("Amount", preset.LpfLfoAmount, 20, 20000, 1, formatHertz),
					waveFormNode(preset.LpfLfoShape),
					NewSliderNode("Rate", preset.LpfLfoFreq, 0.01, 20, .01, formatLowHertz),
					NewSliderNode("Phase", preset.LpfLfoPhase, 0, 1, .01, formatCycle),
				),
				adsrNodeWithToggle("ADSR", preset.LpfAdsrOnOff, preset.LpfAdsrAttack, preset.LpfAdsrDecay, preset.LpfAdsrSustain, preset.LpfAdsrRelease,
					NewSliderNode("Amount", preset.LpfAdsrAmount, -20000, 20000, 1, formatHertz),
				),
			),
			NewNode("Pitch",
				NewNode("LFO",
					onOffNode(preset.PitchLfoOnOff),
					NewSliderNode("Amount", preset.PitchLfoAmount, -1000, 1000, .01, formatSemiTon),
					waveFormNode(preset.PitchLfoShape),
					NewSliderNode("Rate", preset.PitchLfoFreq, 0.01, 20, .01, formatLowHertz),
					NewSliderNode("Phase", preset.PitchLfoPhase, 0, 1, .01, formatCycle),
				),
				adsrNodeWithToggle("ADSR", preset.PitchAdsrOnOff, preset.PitchAdsrAttack, preset.PitchAdsrDecay, preset.PitchAdsrSustain, preset.PitchAdsrRelease,
					NewSliderNode("Amount", preset.PitchAdsrAmount, -1000, 1000, .01, formatSemiTon),
				),
			),
		),
		NewNode("Effects",
			NewNode("Feedback delay",
				onOffNode(preset.FBOnOff),
				NewSliderNode("Delay", preset.FBDelayParam, 0, 2, .001, formatMillisecond),
				NewSliderNode("Feedback", preset.FBFeedBack, 0, 0.95, .01, nil),
				NewSliderNode("Mix", preset.FBMix, 0, 1, .01, nil),
				NewSliderNode("Tone", preset.FBTone, 200, 8000, 1, formatHertz),
			),
			NewNode("Low pass filter",
				onOffNode(preset.LPFOnOff),
				NewSliderNode("Cutoff", preset.LPFCutoff, 20, 20000, 1, formatHertz),
				NewSliderNode("Resonance", preset.LPFResonance, 0.01, 10, .01, nil),
			),
			NewNode("Unison",
				onOffNode(preset.UnisonOnOff),
				NewSliderNode("Voices", preset.UnisonVoices, 1, 16, 1, func(v float32) string {
					return fmt.Sprintf("%.0f voices", v)
				}),
				NewSliderNode("Pan spread", preset.UnisonPanSpread, 0, 1, .01, nil),
				NewSliderNode("Phase spread", preset.UnisonPhaseSpread, 0, 1, .01, formatCycle),
				NewSliderNode("Detune spread", preset.UnisonDetuneSpread, 0, 100, .1, formatCent),
				NewSliderNode("Curve gamma", preset.UnisonCurveGamma, 0.1, 4, .1, nil),
			),
		),
		NewNode("Visualizer",
			NewFeatureNode("Spectrum", 0), // todo Placeholder feature for future implementation
			NewFeatureNode("Oscilloscope", FeatureOscilloscope),
		),
		NewNode("Presets",
			allPresetsNodes("assets/presets/", logger)...,
		),
		NewNode("Settings",
			NewNode("General"),
			NewNode("Master gain"),
			NewNode("MIDI controller"),
			NewNode("Pitch bend"),
			NewNode("About"),
		),
	)
}
